projectName: Top 5 Threat Detection Solutions for Small Businesses in us
baseUrl: https://gracker.ai
homeLink: https://gracker.ai/
logoLink: https://gracker.ai/
ctaText: Get Started
aboutLink: https://gracker.ai/about
productsLink: https://gracker.ai/products
portalHeading: AI-powered Cybersecurity Marketing Solution
portalDescription: >-
  World's first AI-driven growth engine for cybersecurity B2B SaaS. Engage
  prospects, demonstrate expertise, and fuel expansion through customized,
  data-backed content strategies.
portalTitle: Top Threat Detection Solutions for Small Businesses
searchPlaceholder: Search for solutions...
logoImgUrl: https://gracker.ai/_astro/logo-white.DuNP12gY_Z22gpAz.svg
ctaLink: https://gracker.ai/demo/
googleTagManagerId: GTM-TPM6JQPC
copyrightText: © Copyright 2024, Gracker.
faviconUrl: https://gracker.ai/favicon.ico
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
socialLinks:
  - platform: LinkedIn
    url: https://www.linkedin.com/company/gracker-ai/
  - platform: Twitter
    url: https://x.com/grackerAI
  - platform: Instagram
    url: https://www.instagram.com/grackerai/
theme:
  primaryColor: '#ffffff'
  secondaryColor: '#000000'
  backgroundColor: '#f2f2f2'
  textColor: '#000000'
  accentColor: '#ff5722'
fonts:
  - family: Bricolage Grotesque
    weights:
      - 400
      - 500
      - 600
  - family: Poppins
    weights:
      - 400
      - 500
      - 600
